name: Tests

on:
    push:
        branches: [main]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [8.2, 8.3, 8.4]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  tools: composer:v2

            - name: Validate composer.json
              run: composer validate --strict

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-interaction

            - name: Run tests
              run: composer test
